version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    links:
      - php
    networks:
      - app-network

  php:
    image: php:8.1-fpm
    volumes:
      - ./public:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: docker_test_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: dockerpass
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge